export const altAttributes = {
  "aberdeen-jumbo.avif":
    "Aberdeen channel with the late Jumbo floating restaurant.",
  "golden-hour.avif": "",
  "mei-foo-icc.avif": "International Commerce Centre from Mei Foo.",
  "sham-shui-po-men.avif":
    "Men reading newspapers outside the Jockey Club in Sham Shui Po.",
  "austin-taxis.avif": "",
  "golf-course.avif": "",
  "monster-house-sign.avif": "",
  "sharp-island.avif": "",
  "autumn-foliage.avif": "Rare autumn foliage in the northern New Territories.",
  "green-village.avif": "",
  "monster-house.avif": "The Monster Building in Quarry Bay.",
  "small-boats.avif": "",
  "bridge.avif": "Ting Kau Bridge.",
  "happy-valley-racecourse.avif": "Happy Valley Racecourse at night.",
  "plover-cove-dam.avif": "",
  "tai-mei-tuk-dam.avif": "",
  "bridge2.avif": "",
  "island-causeway.avif": "",
  "pok-fu-lam-sea.avif": "",
  "tai-mo-shan-clouds.avif":
    "View from Tai Mo Shan, the highest peak in Hong Kong.",
  "cheung-chau-basketball.avif":
    "Basketball court next to the beach on Cheung Chau Island.",
  "jordan-clothes.avif": "Street view in Jordan, Kowloon.",
  "pui-o-cows.avif": "Cows walking on Pui O beach.",
  "taxi-on-dam.avif": "",
  "cheung-chau.avif": "Cheung Chau Island.",
  "jordan-houses.avif": "Jordan, Kowloon.",
  "sai-kung-beaches.avif":
    "Sharp Peak and the four beaches: Tung Wan, Tai Wan, Ham Tin, and Sai Wan.",
  "taxis-and-minibus.avif": "",
  "choi-hung-house.avif": "",
  "jordan-minibus.avif": "",
  "sai-kung-dam.avif": "",
  "taxis-tst.avif": "",
  "clockenflap.avif":
    "Concert at the Clockenflap music festival at the Central Harbourfront.",
  "jordan-school.avif": "",
  "sai-kung-island.avif": "",
  "to-kwa-wan-houses.avif": "Tightly packed houses in To Kwa Wan, Kowloon.",
  "coffers.avif": "",
  "kornhill-house.avif": "Residential building in Kornhill.",
  "sai-kung-pier.avif": "",
  "tst-badminton.avif": "",
  "concrete.avif": "",
  "kornhill.avif": "",
  "sai-kung-taxis.avif": "",
  "west-kowloon-tunnel.avif": "",
  "gold-coast.avif": "",
  "lamma-lizard.avif": "Man with a pet lizard on Lamma Island.",
  "scaffolding.avif":
    "Scaffolding being assembled for a high-rise building in Causeway Bay.",
  "yellow-hill.avif": "",
};
